/**
 * Generates public/sitemap.xml from the route registry.
 *
 * The sitemap used to be written by the prerender pipeline. That pipeline
 * retired with the move to SSR and nothing replaced it, so the file became
 * hand-maintained: every new page needed someone to remember, and nothing
 * failed if they didn't. /test-de-nivel was added by hand for exactly that
 * reason.
 *
 * Membership is derived, not typed: a route belongs in the sitemap unless it
 * canonicalises somewhere else (a retired alias like /cursuri-araba, which
 * would otherwise ask to be indexed and then point away) or it is noindex
 * (/stergere-date). That rule reproduces the existing file exactly.
 *
 * changefreq and priority are curated per page rather than derived, so they are
 * read back from the current file and preserved; only genuinely new URLs get a
 * default. Losing that curation on every build would be a silent regression in
 * a file nobody reads closely.
 *
 * src/test/sitemap.test.ts asserts the committed file matches this output, so
 * forgetting to run the build fails the suite instead of shipping a stale map.
 *
 * Pure by design: this module only builds the string. scripts/generateSitemap.ts
 * writes it, so the test can import and compare without rewriting the file it
 * is checking.
 */
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { allSeoRoutes, type SeoRoute } from "@/lib/seoHead";

const BASE = "https://centruldearabalibaneza.com";
const FILE = resolve(process.cwd(), "public/sitemap.xml");
const DEFAULT_FREQ = "monthly";
const DEFAULT_PRIORITY = "0.6";

/** A route is listed unless it points its canonical elsewhere, or is noindex. */
export const belongsInSitemap = (r: SeoRoute): boolean => !r.canonical && !r.noindex;

/** Existing curation, keyed by path, so regenerating does not flatten it. */
function existingSettings(): Map<string, { changefreq: string; priority: string }> {
  const out = new Map<string, { changefreq: string; priority: string }>();
  if (!existsSync(FILE)) return out;
  const xml = readFileSync(FILE, "utf8");
  for (const block of xml.split("<url>").slice(1)) {
    const loc = /<loc>([^<]+)<\/loc>/.exec(block)?.[1];
    if (!loc) continue;
    out.set(loc.replace(BASE, "") || "/", {
      changefreq: /<changefreq>([^<]+)<\/changefreq>/.exec(block)?.[1] ?? DEFAULT_FREQ,
      priority: /<priority>([^<]+)<\/priority>/.exec(block)?.[1] ?? DEFAULT_PRIORITY,
    });
  }
  return out;
}

export function buildSitemap(): string {
  const curated = existingSettings();
  const urls = allSeoRoutes()
    .filter(belongsInSitemap)
    .map((r) => {
      const s = curated.get(r.path) ?? { changefreq: DEFAULT_FREQ, priority: DEFAULT_PRIORITY };
      return `  <url>\n    <loc>${BASE}${r.path}</loc>\n    <changefreq>${s.changefreq}</changefreq>\n    <priority>${s.priority}</priority>\n  </url>`;
    });
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generateSitemap.ts from the route registry in",
    "     src/lib/seoHead.ts. Do not edit by hand: run the build, or the check in",
    "     src/test/sitemap.test.ts will disagree with you. Routes that canonicalise",
    "     elsewhere and noindex routes are excluded. No <lastmod>: we have no",
    "     per-page change timestamps. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    "</urlset>",
    "",
  ].join("\n");
}
