/**
 * Generates public/sitemap.xml from the route registry.
 *
 * The sitemap used to be written by the prerender pipeline. That pipeline
 * retired with the move to SSR and nothing replaced it, so the file became
 * hand-maintained: every new page needed someone to remember, and nothing
 * failed if they didn't. /test-de-nivel was added by hand for exactly that
 * reason.
 *
 * Membership is derived, not typed: a route belongs in the sitemap unless it
 * canonicalises somewhere else (a retired alias like /cursuri-araba, which
 * would otherwise ask to be indexed and then point away) or it is noindex
 * (/stergere-date). That rule reproduces the existing file exactly.
 *
 * changefreq and priority are curated per page rather than derived, so they are
 * read back from the current file and preserved; only genuinely new URLs get a
 * default. Losing that curation on every build would be a silent regression in
 * a file nobody reads closely.
 *
 * src/test/sitemap.test.ts asserts the committed file matches this output, so
 * forgetting to run the build fails the suite instead of shipping a stale map.
 *
 * <lastmod> is passed in, not computed here. A real per-page date is the one
 * signal that tells a crawler which of 121 URLs is worth fetching again, and
 * after a change that rewrote every head it is the difference between "we know
 * about this page" and "this page changed, come back". The dates come from git,
 * which only scripts/generateSitemap.ts can read; this module stays pure, so
 * src/test/sitemap.test.ts can compare structure without a git call. A URL with
 * no date simply has no lastmod, which is better than a made-up one — Google
 * ignores a sitemap whose dates are all identical or obviously wrong.
 *
 * Pure by design: this module only builds the string. scripts/generateSitemap.ts
 * writes it, so the test can import and compare without rewriting the file it
 * is checking.
 */
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { allSeoRoutes, type SeoRoute } from "@/lib/seoHead";
import { blogPageHref, blogTotalPages } from "@/lib/blogPagination";

const BASE = "https://centruldearabalibaneza.com";
const FILE = resolve(process.cwd(), "public/sitemap.xml");
const DEFAULT_FREQ = "monthly";
const DEFAULT_PRIORITY = "0.6";

/** A route is listed unless it points its canonical elsewhere, or is noindex. */
export const belongsInSitemap = (r: SeoRoute): boolean => !r.canonical && !r.noindex;

/** Existing curation, keyed by path, so regenerating does not flatten it. */
function existingSettings(): Map<string, { changefreq: string; priority: string }> {
  const out = new Map<string, { changefreq: string; priority: string }>();
  if (!existsSync(FILE)) return out;
  const xml = readFileSync(FILE, "utf8");
  for (const block of xml.split("<url>").slice(1)) {
    const loc = /<loc>([^<]+)<\/loc>/.exec(block)?.[1];
    if (!loc) continue;
    out.set(loc.replace(BASE, "") || "/", {
      changefreq: /<changefreq>([^<]+)<\/changefreq>/.exec(block)?.[1] ?? DEFAULT_FREQ,
      priority: /<priority>([^<]+)<\/priority>/.exec(block)?.[1] ?? DEFAULT_PRIORITY,
    });
  }
  return out;
}

/**
 * The blog index beyond page one.
 *
 * /blog?page=2 holds nine articles and is the only page that lists them
 * together; it is self-canonical, so it belongs here. It was missing, which left
 * the deeper half of the blog reachable by one link and nothing else.
 */
export function blogIndexPages(): string[] {
  const out: string[] = [];
  for (const base of ["/blog", "/en/blog"]) {
    for (let page = 2; page <= blogTotalPages(); page += 1) out.push(blogPageHref(base, page));
  }
  return out;
}

export function buildSitemap(lastmods: ReadonlyMap<string, string> = new Map()): string {
  const curated = existingSettings();
  const entry = (path: string, changefreq: string, priority: string) => {
    const lastmod = lastmods.get(path);
    // A URL in a sitemap is XML: an ampersand in a query string has to be
    // escaped. Only ?page= uses one today; this keeps the next one valid too.
    const loc = `${BASE}${path}`.replace(/&/g, "&amp;");
    return (
      `  <url>\n    <loc>${loc}</loc>\n` +
      (lastmod ? `    <lastmod>${lastmod}</lastmod>\n` : "") +
      `    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`
    );
  };
  const urls = allSeoRoutes()
    .filter(belongsInSitemap)
    .map((r) => {
      const s = curated.get(r.path) ?? { changefreq: DEFAULT_FREQ, priority: DEFAULT_PRIORITY };
      return entry(r.path, s.changefreq, s.priority);
    })
    .concat(
      blogIndexPages().map((path) => {
        const s = curated.get(path) ?? { changefreq: "weekly", priority: "0.5" };
        return entry(path, s.changefreq, s.priority);
      }),
    );
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generateSitemap.ts from the route registry in",
    "     src/lib/seoHead.ts. Do not edit by hand: run the build, or the check in",
    "     src/test/sitemap.test.ts will disagree with you. Routes that canonicalise",
    "     elsewhere and noindex routes are excluded. <lastmod> is the date of the",
    "     last commit that touched the page itself, read from git at build time. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    "</urlset>",
    "",
  ].join("\n");
}
