// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-pricing.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
var ONLINE_PRICES = {
  groupMonthly: { A1: 500, A2: 600, B1: 700, B2: 800, C1: 900, C2: 1e3 },
  privateLesson: 150,
  kidsPrivateLesson: 150,
  kidsGroupMonthly: 500
};
var round10 = (n) => Math.round(n / 10) * 10;
var physicalPrice = (online) => round10(online * 1.4);
var get_pricing_default = defineTool({
  name: "get_pricing",
  title: "Get course pricing",
  description: "Return current pricing (LEI) for all course formats offered by Arab\u0103 Libanez\u0103 cu Ibra: group monthly per CEFR level, private 1:1, and kids programs. Includes both online and physical (in-center) prices.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const groupMonthly = Object.fromEntries(
      Object.entries(ONLINE_PRICES.groupMonthly).map(([lvl, online]) => [
        lvl,
        { online, fizic: physicalPrice(online), unit: "LEI/month" }
      ])
    );
    const pricing = {
      currency: "LEI",
      groupMonthly,
      privateLesson: {
        online: ONLINE_PRICES.privateLesson,
        fizic: physicalPrice(ONLINE_PRICES.privateLesson),
        unit: "LEI/lesson"
      },
      kidsPrivateLesson: {
        online: ONLINE_PRICES.kidsPrivateLesson,
        fizic: physicalPrice(ONLINE_PRICES.kidsPrivateLesson),
        unit: "LEI/lesson"
      },
      kidsGroupMonthly: {
        online: ONLINE_PRICES.kidsGroupMonthly,
        fizic: physicalPrice(ONLINE_PRICES.kidsGroupMonthly),
        unit: "LEI/month/child (min. 4)"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
      structuredContent: pricing
    };
  }
});

// src/lib/mcp/tools/list-curriculum-levels.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var LEVELS = [
  { id: "a1", title: "A1 \u2014 Beginner (Survival)", lessons: 32, hours: 48, track: "Spoken", schedule: "In person (Group 2): Mon & Wed 19:00\u201320:30, 2 Sep \u2013 21 Dec 2026 (32 lessons), Strada Icoanei 80 \xB7 enrollment open, limited spots \xB7 Online: Sat 12:00\u201313:30 and Sun 17:30\u201319:00, group in progress and full" },
  { id: "a2", title: "A2 \u2014 Elementary", lessons: 54, hours: 81, track: "Spoken", schedule: "In person: Tue & Thu 19:00\u201320:30, 1 Sep 2026 \u2013 4 Mar 2027 (54 lessons), Strada Icoanei 80 \xB7 runs in parallel with A1 \xB7 enrollment open, limited spots" },
  { id: "b1", title: "B1 \u2014 Intermediate", lessons: 70, hours: 105, track: "Spoken", schedule: "~8 months \xB7 opens after A2 \u2014 future enrollment" },
  { id: "b2", title: "B2 \u2014 Upper-Intermediate", lessons: 70, hours: 105, track: "Spoken", schedule: "~8\u20139 months \xB7 opens after B1 \u2014 future enrollment" },
  { id: "c1", title: "C1 \u2014 Advanced", lessons: 70, hours: 105, track: "Spoken + Written", schedule: "~10 months \xB7 opens after B2 \u2014 future enrollment" },
  { id: "c2", title: "C2 \u2014 Mastery", lessons: 80, hours: 120, track: "Thematic modules", schedule: "~10 months \xB7 opens after C1 \u2014 future enrollment" }
];
var list_curriculum_levels_default = defineTool2({
  name: "list_curriculum_levels",
  title: "List CEFR curriculum levels",
  description: "List the six CEFR levels (A1\u2013C2) offered for Lebanese Arabic, with lesson counts, hours, and track focus.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(LEVELS, null, 2) }],
    structuredContent: { levels: LEVELS }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return public contact details (email, website) for Arab\u0103 Libanez\u0103 cu Ibra.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Arab\u0103 Libanez\u0103 cu Ibra",
      instructor: "Ibra",
      email: "marhaba@centruldearabalibaneza.com",
      website: "https://centruldearabalibaneza.com",
      languages: ["ro", "en"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "araba-libaneza-mcp",
  title: "Arab\u0103 Libanez\u0103 cu Ibra",
  version: "0.1.0",
  instructions: "Public tools for the Arab\u0103 Libanez\u0103 cu Ibra Lebanese-Arabic language school. Use `get_pricing` for course fees (LEI), `list_curriculum_levels` for the CEFR A1\u2013C2 structure, and `get_contact_info` for how to reach the school.",
  // Upstream @lovable.dev/mcp-js types declare outputSchema as required ZodRawShape,
  // which conflicts with exactOptionalPropertyTypes for tools without one.
  tools: [get_pricing_default, list_curriculum_levels_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
