// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-pricing.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { ONLINE_PRICES, physicalPrice } from "npm:@/lib/pricing";
var get_pricing_default = defineTool({
  name: "get_pricing",
  title: "Get course pricing",
  description: "Return current pricing (LEI) for all course formats offered by Arab\u0103 Libanez\u0103 cu Ibra: group monthly per CEFR level, private 1:1, and kids programs. Includes both online and physical (in-center) prices.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const groupMonthly = Object.fromEntries(
      Object.entries(ONLINE_PRICES.groupMonthly).map(([lvl, online]) => [
        lvl,
        { online, fizic: physicalPrice(online), unit: "LEI/month" }
      ])
    );
    const pricing = {
      currency: "LEI",
      groupMonthly,
      privateLesson: {
        online: ONLINE_PRICES.privateLesson,
        fizic: physicalPrice(ONLINE_PRICES.privateLesson),
        unit: "LEI/lesson"
      },
      kidsPrivateLesson: {
        online: ONLINE_PRICES.kidsPrivateLesson,
        fizic: physicalPrice(ONLINE_PRICES.kidsPrivateLesson),
        unit: "LEI/lesson"
      },
      kidsGroupMonthly: {
        online: ONLINE_PRICES.kidsGroupMonthly,
        fizic: physicalPrice(ONLINE_PRICES.kidsGroupMonthly),
        unit: "LEI/month/child (min. 4)"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(pricing, null, 2) }],
      structuredContent: pricing
    };
  }
});

// src/lib/mcp/tools/list-curriculum-levels.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var LEVELS = [
  { id: "a1", title: "A1 \u2014 Beginner (Survival)", lessons: 30, hours: 45, track: "Spoken" },
  { id: "a2", title: "A2 \u2014 Elementary", lessons: 30, hours: 45, track: "Spoken" },
  { id: "b1", title: "B1 \u2014 Intermediate", lessons: 30, hours: 45, track: "Spoken" },
  { id: "b2", title: "B2 \u2014 Upper-Intermediate", lessons: 30, hours: 45, track: "Spoken" },
  { id: "c1", title: "C1 \u2014 Advanced", lessons: 30, hours: 45, track: "Spoken + Written" },
  { id: "c2", title: "C2 \u2014 Mastery", lessons: 30, hours: 45, track: "Thematic modules" }
];
var list_curriculum_levels_default = defineTool2({
  name: "list_curriculum_levels",
  title: "List CEFR curriculum levels",
  description: "List the six CEFR levels (A1\u2013C2) offered for Lebanese Arabic, with lesson counts, hours, and track focus.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(LEVELS, null, 2) }],
    structuredContent: { levels: LEVELS }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return public contact details (email, website) for Arab\u0103 Libanez\u0103 cu Ibra.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Arab\u0103 Libanez\u0103 cu Ibra",
      instructor: "Ibra",
      email: "marhaba@centruldearabalibaneza.com",
      website: "https://centruldearabalibaneza.com",
      languages: ["ro", "en"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "araba-libaneza-mcp",
  title: "Arab\u0103 Libanez\u0103 cu Ibra",
  version: "0.1.0",
  instructions: "Public tools for the Arab\u0103 Libanez\u0103 cu Ibra Lebanese-Arabic language school. Use `get_pricing` for course fees (LEI), `list_curriculum_levels` for the CEFR A1\u2013C2 structure, and `get_contact_info` for how to reach the school.",
  tools: [get_pricing_default, list_curriculum_levels_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
